# Generated by Django 4.1.6 on 2024-03-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question1", models.CharField(max_length=100)),
                ("question2", models.CharField(max_length=100)),
                ("question3", models.CharField(max_length=100)),
                ("question4", models.CharField(max_length=100)),
                ("question5", models.CharField(max_length=100)),
                ("question6", models.CharField(max_length=100)),
                ("question7", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.customuser"
                    ),
                ),
            ],
        ),
    ]
