# Generated by Django 4.1.6 on 2024-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Option",
        ),
    ]
